//#############################################################################
//# Function: 2-Input Glitch-Free Clock Mux                                   #
//# Copyright: Lambda Project Authors. All rights Reserved.                   #
//# License:  MIT (see LICENSE file in Lambda repository)                     #
//#############################################################################

/* Glitch-free 2-input clock mux with feedback handshake. The handshake
 * ensures one clock is fully gated before the other is enabled, preventing
 * output glitches during switchover.
 *
 * clk0 is the default clock and must always be running. It propagates
 * through the mux during reset. An absence of clk0 typically requires a
 * full system reset to recover. clk1 does not need to be running at all
 * times, but the handshake requires both clocks to be toggling for a
 * sel transition to complete.
 *
 * WARNING: If clk1 is generated by logic clocked from 'out', switching
 * to clk1 (sel=1) will stop 'out' when clk1 stops, making the control
 * registers unreachable. Always switch back to clk0 (sel=0) before
 * modifying logic that produces clk1.
 *
 */

module la_clkmux2 #(parameter PROP = "DEFAULT" // cell property
                    )
   (
    input  clk0,   // default clock (enabled during reset)
    input  clk1,
    input  nreset, // async active low reset
    input  sel,    // 1=clk1, 0=clk0
    output out
    );

`ifdef VERILATOR

   // Reduced-order Verilator-safe model. In real silicon, the glitch-free
   // clock mux uses ICG cells with no combinational clock-to-output path.
   // This dual-edge register approximation breaks that dependency.
   initial
     $display("WARNING: Reduced order verilator model used for la_clkmux2.");

   reg out_reg;
   always @(posedge clk0 or negedge clk0 or posedge clk1 or negedge clk1 or negedge nreset)
     if (!nreset)
       out_reg <= clk0;
     else
       out_reg <= sel ? clk1 : clk0;
   assign out = out_reg;
`else
   // local wires
   wire       selb;
   wire [1:0] en;
   wire [1:0] ensync;
   wire [1:0] maskb;
   wire [1:0] clkg;
   wire       en0b;
   wire       ensync0b;

   // Handshake logic: each path is enabled only after the other is gated off
   la_inv isel (.a(sel),
                .z(selb));

   la_inv inv0 (.a(ensync[0]),
                .z(maskb[0]));

   la_inv inv1 (.a(ensync[1]),
                .z(maskb[1]));

   la_and2 ien0 (.a(selb),
                 .b(maskb[1]), // enable once clk1 path is gated off
                 .z(en[0]));

   la_and2 ien1 (.a(sel),
                 .b(maskb[0]), // enable once clk0 path is gated off
                 .z(en[1]));

   // Invert en[0] before and after the sync so that the clk0 path resets
   // to enabled (la_drsync resets to 0; inverted, that becomes 1).
   la_inv ien0b (.a(en[0]),
                 .z(en0b));

   la_drsync isync0 (.clk    (clk0),
                     .nreset (nreset),
                     .in     (en0b),
                     .out    (ensync0b));

   la_inv iensync0 (.a(ensync0b),
                    .z(ensync[0]));

   la_drsync isync1 (.clk    (clk1),
                     .nreset (nreset),
                     .in     (en[1]),
                     .out    (ensync[1]));

   // Glitch-free clock gating
   la_clkicgand igate0 (.clk  (clk0),
                        .te   (1'b0),
                        .en   (ensync[0]),
                        .eclk (clkg[0]));

   la_clkicgand igate1 (.clk  (clk1),
                        .te   (1'b0),
                        .en   (ensync[1]),
                        .eclk (clkg[1]));

   // OR the mutually exclusive gated clocks
   la_clkor2 iorclk (.a(clkg[0]),
                     .b(clkg[1]),
                     .z(out));
`endif

endmodule
